version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pdf_chat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dev/init-pg-vector.sql:/docker-entrypoint-initdb.d/init-pg-vector.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres && psql -U postgres -d pdf_chat -c \"SELECT 1 FROM pg_extension WHERE extname = 'vector'\""]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DOCUMENT_STORE_TYPE=${DOCUMENT_STORE_TYPE}
      - DB_HOST=db
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: